cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
brew 'mas'

brew 'bash-completion'
brew 'gnutls'

brew 'git'
brew 'gh'

brew 'bat'
brew 'fd'
brew 'graphviz'
brew 'htop'
brew 'imagemagick'
brew 'rename'
brew 'rg'
brew 'rlwrap'
brew 'tree'
brew 'wget'
brew 'jsonpp'
brew 'jq'

cask '1password'
cask 'dropbox'
cask 'visual-studio-code'

mas 'Things 3', id: 904280696
mas 'iA Writer', id: 775737590
mas 'Pixelmator Pro', id: 1289583905
mas '1Password for Safari', id: 1569813296

cask 'font-ia-writer-duospace'
cask 'font-inter'
